version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: risk-radar:latest
    container_name: risk-radar-api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend/app:/app
      - ./backend/model_cache:/app/model_cache
    ports:
      - "8000:8000"
    restart: unless-stopped
  
  postgres:
    image: postgres:15-alpine
    container_name: risk-radar-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U riskradar"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
volumes:
  postgres_data: